//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityScriptures.Properties {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class UScriptureSettings : global::System.Configuration.ApplicationSettingsBase {
		
		private static UScriptureSettings defaultInstance = ((UScriptureSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UScriptureSettings())));
		
		public static UScriptureSettings Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public global::System.Collections.Specialized.StringCollection FavouriteChapters {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["FavouriteChapters"]));
			}
			set {
				this["FavouriteChapters"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public global::System.Collections.Specialized.StringCollection FavouriteVerses {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["FavouriteVerses"]));
			}
			set {
				this["FavouriteVerses"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Trebuchet MS, 12pt")]
		public global::System.Drawing.Font Font {
			get {
				return ((global::System.Drawing.Font)(this["Font"]));
			}
			set {
				this["Font"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool LaunchOnStart {
			get {
				return ((bool)(this["LaunchOnStart"]));
			}
			set {
				this["LaunchOnStart"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public global::System.Collections.Specialized.StringCollection lost {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["lost"]));
			}
			set {
				this["lost"] = value;
			}
		}
	}
}
